select 1
use cadastro
select 2
use empresto
select 3
use devolve
select 4
use nome

tempo_1 = 'NETO (SUPORTE - NUTECNET)'
tempo_2 = 'OTACILIO (SUPORTE - NUTECNET)'

select 1
do while .not. eof()

if nempresto = tempo_1
replace nempresto with tempo_2
endif

skip +1
enddo

select 2
do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 3
do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 4

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

tempo_1 = 'ALEXANDRE CHAR (INFORMAR)'
tempo_2 = 'ALEXANDRE CHAR'

select 1
goto top

do while .not. eof()

if nempresto = tempo_1
replace nempresto with tempo_2
endif

skip +1
enddo

select 2
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 3
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 4
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

tempo_1 = 'ALEXANDRE PALMA (INFORMAR)'
tempo_2 = 'ALEXANDRE FISHER PALMA'

select 1
goto top

do while .not. eof()

if nempresto = tempo_1
replace nempresto with tempo_2
endif

skip +1
enddo

select 2
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 3
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 4
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

tempo_1 = 'CYNTIA (INFORMAR)'
tempo_2 = 'CYNTIA GOLCALVES'

select 1
goto top

do while .not. eof()

if nempresto = tempo_1
replace nempresto with tempo_2
endif

skip +1
enddo

select 2
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 3
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 4
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

tempo_1 = 'ERIC (INFORMAR)'
tempo_2 = 'ERIC BIONDI DO AMARAL'

select 1
goto top

do while .not. eof()

if nempresto = tempo_1
replace nempresto with tempo_2
endif

skip +1
enddo

select 2
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 3
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 4
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

tempo_1 = 'ROBERTO (INFORMAR)'
tempo_2 = 'ROBERTO HUMMEL JUNIOR'

select 1
goto top

do while .not. eof()

if nempresto = tempo_1
replace nempresto with tempo_2
endif

skip +1
enddo

select 2
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 3
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 4
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

tempo_1 = 'SIDNEY (INFORMAR)'
tempo_2 = 'SIDNEY PEREIRA DOS SANTOS'

select 1
goto top

do while .not. eof()

if nempresto = tempo_1
replace nempresto with tempo_2
endif

skip +1
enddo

select 2
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 3
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 4
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

tempo_1 = 'ELISEU (INFORMAR)'
tempo_2 = 'ELISEU DE MELO SIQUEIRA'

select 1
goto top

do while .not. eof()

if nempresto = tempo_1
replace nempresto with tempo_2
endif

skip +1
enddo

select 2
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 3
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 4
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

tempo_1 = 'LUIS (INFORMAR)'
tempo_2 = 'LUIS ANTONIO GARCIA MARZAGAO'

select 1
goto top

do while .not. eof()

if nempresto = tempo_1
replace nempresto with tempo_2
endif

skip +1
enddo

select 2
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 3
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 4
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

tempo_1 = 'AILTON (INFORMAR)'
tempo_2 = 'JOSE AILTON DIONISIO DO NASCIMENTO'

select 1
goto top

do while .not. eof()

if nempresto = tempo_1
replace nempresto with tempo_2
endif

skip +1
enddo

select 2
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 3
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 4
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

tempo_1 = 'ROBERTO (INFORMAR - VENDA)'
tempo_2 = 'ROBERTO HUMMEL JUNIOR (VENDA)'

select 1
goto top

do while .not. eof()

if nempresto = tempo_1
replace nempresto with tempo_2
endif

skip +1
enddo

select 2
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 3
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 4
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

tempo_1 = 'ROBERTO (INFORMAR)'
tempo_2 = 'ROBERTO HUMMEL JUNIOR'

select 1
goto top

do while .not. eof()

if nempresto = tempo_1
replace nempresto with tempo_2
endif

skip +1
enddo

select 2
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 3
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

select 4
goto top

do while .not. eof()

if nome = tempo_1
replace nome with tempo_2
endif

skip +1
enddo

delete file cadastro.ntx
delete file empresto.ntx
delete file devolve.ntx
delete file nome.ntx
